// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://mxjjqimwmkcvpqvbdtfo.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14ampxaW13bWtjdnBxdmJkdGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE2NjQwNDAsImV4cCI6MjA0NzI0MDA0MH0.yNycBlC5-eQZ70Zc8EqU1krQHKHGkUjcTIeiGOoJWco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);